# Generated by Django 4.2.7 on 2025-10-10 17:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la inmobiliaria', max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(help_text='Email corporativo de la inmobiliaria', max_length=254, unique=True, verbose_name='email')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(help_text='Teléfono de contacto en formato internacional', max_length=128, region=None, verbose_name='teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física de la inmobiliaria', null=True, verbose_name='dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='país')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='código postal')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='sitio web')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la inmobiliaria', max_length=1000, null=True, verbose_name='descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='inmobiliarias/logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la inmobiliaria está activa en el sistema', verbose_name='activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Inmobiliaria',
                'verbose_name_plural': 'Inmobiliarias',
                'db_table': 'users_inmobiliaria',
                'ordering': ['nombre'],
            },
        ),
    ]
