from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    RoleViewSet,
    PermissionViewSet,
    UserRoleManagementView,
    RoleStatsView,
    UserRoleHistoryView
)

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'', RoleViewSet, basename='role')
router.register(r'permissions', PermissionViewSet, basename='permission')

urlpatterns = [
    # Role and Permission CRUD operations via ViewSets
    path('', include(router.urls)),
    
    # User role management endpoints
    path('users/<int:user_id>/assign-role/', UserRoleManagementView.as_view(), name='assign-user-role'),
    path('users/<int:user_id>/role-history/', UserRoleHistoryView.as_view(), name='user-role-history'),
    path('users/role-history/', UserRoleHistoryView.as_view(), name='my-role-history'),
    
    # Statistics endpoint
    path('stats/', RoleStatsView.as_view(), name='role-stats'),
]

# URL patterns generated by the router:
# GET /roles/ - List all roles
# POST /roles/ - Create a new role (Admin only)
# GET /roles/{id}/ - Retrieve a specific role
# PUT /roles/{id}/ - Update a specific role (Admin only)
# PATCH /roles/{id}/ - Partially update a specific role (Admin only)
# DELETE /roles/{id}/ - Delete a specific role (Admin only)
# POST /roles/{id}/add-permission/ - Add permission to role (Admin only)
# POST /roles/{id}/remove-permission/ - Remove permission from role (Admin only)

# GET /roles/permissions/ - List all permissions
# POST /roles/permissions/ - Create a new permission (Admin only)
# GET /roles/permissions/{id}/ - Retrieve a specific permission
# PUT /roles/permissions/{id}/ - Update a specific permission (Admin only)
# PATCH /roles/permissions/{id}/ - Partially update a specific permission (Admin only)
# DELETE /roles/permissions/{id}/ - Delete a specific permission (Admin only)