# Generated by Django 4.2.7 on 2025-10-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la actividad', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la actividad')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada telefónica'), ('reunion', 'Reunión'), ('visita', 'Visita a propiedad'), ('seguimiento', 'Seguimiento de cliente'), ('documentacion', 'Gestión de documentos'), ('marketing', 'Actividad de marketing'), ('prospección', 'Prospección de clientes'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pospuesta', 'Pospuesta')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_programada', models.DateTimeField(help_text='Fecha y hora programada para la actividad')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha límite para completar', null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales o comentarios')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación donde se realizará la actividad', max_length=300)),
                ('duracion_estimada', models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(help_text='Usuario responsable de la actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó la actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_programada', '-prioridad'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='activities__estado_995de6_idx'), models.Index(fields=['asignado_a', 'estado'], name='activities__asignad_9a0227_idx'), models.Index(fields=['tipo', 'estado'], name='activities__tipo_2061f6_idx')],
            },
        ),
    ]
