# Generated by Django 4.2.7 on 2025-10-09 15:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Contrato')),
                ('contract_type', models.CharField(choices=[('sale', 'Compraventa'), ('rent', 'Arrendamiento'), ('lease', 'Arrendamiento Comercial'), ('management', 'Administración'), ('exclusive', 'Exclusividad'), ('option', 'Opción de Compra')], max_length=20, verbose_name='Tipo de Contrato')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('active', 'Activo'), ('signed', 'Firmado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('expired', 'Vencido'), ('suspended', 'Suspendido')], default='draft', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente')),
                ('client_address', models.TextField(blank=True, verbose_name='Dirección del Cliente')),
                ('property_address', models.TextField(verbose_name='Dirección de la Propiedad')),
                ('property_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Propiedad')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor del Contrato')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Tasa de Comisión (%)')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de Comisión')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('special_clauses', models.TextField(blank=True, verbose_name='Cláusulas Especiales')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('contract_file', models.CharField(blank=True, max_length=255, verbose_name='Archivo del Contrato')),
                ('attachments', models.TextField(blank=True, verbose_name='Archivos Adjuntos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Agente Responsable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('initial', 'Pago Inicial'), ('monthly', 'Cuota Mensual'), ('commission', 'Comisión'), ('penalty', 'Multa'), ('deposit', 'Depósito'), ('final', 'Pago Final')], max_length=20, verbose_name='Tipo de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('partial', 'Parcial'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pago de Contrato',
                'verbose_name_plural': 'Pagos de Contratos',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('important', 'Importante'), ('reminder', 'Recordatorio'), ('issue', 'Problema'), ('update', 'Actualización')], default='general', max_length=20, verbose_name='Tipo de Nota')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('is_important', models.BooleanField(default=False, verbose_name='Es Importante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_notes', to='contracts.contract', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Nota de Contrato',
                'verbose_name_plural': 'Notas de Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('document_type', models.CharField(choices=[('contract', 'Contrato Principal'), ('addendum', 'Adenda'), ('certificate', 'Certificado'), ('invoice', 'Factura'), ('receipt', 'Recibo'), ('legal', 'Documento Legal'), ('technical', 'Documento Técnico'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('file_path', models.CharField(max_length=255, verbose_name='Ruta del Archivo')),
                ('file_size', models.CharField(blank=True, max_length=20, verbose_name='Tamaño del Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='Contrato')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contratos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'contract_type'], name='contracts_c_status_aff41a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['agent', 'status'], name='contracts_c_agent_i_d94443_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_f953e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['priority', 'status'], name='contracts_c_priorit_c8422d_idx'),
        ),
    ]
