# Generated by Django 4.2.7 on 2025-10-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=100, verbose_name='Nombre del Gráfico')),
                ('chart_type', models.CharField(choices=[('line', 'Línea'), ('bar', 'Barras'), ('pie', 'Circular'), ('doughnut', 'Dona'), ('area', 'Área')], max_length=20, verbose_name='Tipo de Gráfico')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Dato de Gráfico',
                'verbose_name_plural': 'Datos de Gráficos',
                'ordering': ['chart_name', 'date', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('metric_type', models.CharField(choices=[('total_properties', 'Total de Propiedades'), ('active_clients', 'Clientes Activos'), ('pending_contracts', 'Contratos Pendientes'), ('monthly_revenue', 'Ingresos Mensuales'), ('new_leads', 'Nuevos Leads'), ('completed_activities', 'Actividades Completadas')], max_length=50, verbose_name='Tipo de Métrica')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Anterior')),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cambio Porcentual')),
                ('icon', models.CharField(default='fas fa-chart-line', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
                'ordering': ['metric_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('property_added', 'Propiedad Agregada'), ('client_registered', 'Cliente Registrado'), ('contract_signed', 'Contrato Firmado'), ('meeting_scheduled', 'Reunión Programada'), ('lead_converted', 'Lead Convertido'), ('payment_received', 'Pago Recibido')], max_length=50, verbose_name='Tipo de Actividad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad Reciente',
                'verbose_name_plural': 'Actividades Recientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
