# Generated by Django 4.2.7 on 2025-10-09 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('sales', 'Reporte de Ventas'), ('properties', 'Reporte de Propiedades'), ('clients', 'Reporte de Clientes'), ('agents', 'Reporte de Agentes'), ('financial', 'Reporte Financiero'), ('marketing', 'Reporte de Marketing'), ('performance', 'Reporte de Rendimiento')], max_length=20, verbose_name='Tipo de Reporte')),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], max_length=20, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('status', models.CharField(choices=[('generating', 'Generando'), ('ready', 'Listo'), ('error', 'Error'), ('expired', 'Expirado')], default='ready', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='Tamaño del Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('auto_refresh', models.BooleanField(default=False, verbose_name='Actualización Automática')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Gráfico')),
                ('chart_type', models.CharField(choices=[('line', 'Líneas'), ('bar', 'Barras'), ('pie', 'Circular'), ('doughnut', 'Dona'), ('area', 'Área'), ('scatter', 'Dispersión'), ('radar', 'Radar')], max_length=20, verbose_name='Tipo de Gráfico')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('x_axis_label', models.CharField(blank=True, max_length=100, verbose_name='Etiqueta Eje X')),
                ('y_axis_label', models.CharField(blank=True, max_length=100, verbose_name='Etiqueta Eje Y')),
                ('show_legend', models.BooleanField(default=True, verbose_name='Mostrar Leyenda')),
                ('show_grid', models.BooleanField(default=True, verbose_name='Mostrar Grilla')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='reports.report', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Gráfico de Reporte',
                'verbose_name_plural': 'Gráficos de Reportes',
                'ordering': ['report', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color')),
                ('series_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Serie')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reports.reportchart', verbose_name='Gráfico')),
            ],
            options={
                'verbose_name': 'Dato de Gráfico',
                'verbose_name_plural': 'Datos de Gráficos',
                'ordering': ['chart', 'order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Reporte de Ventas'), ('properties', 'Reporte de Propiedades'), ('clients', 'Reporte de Clientes'), ('agents', 'Reporte de Agentes'), ('financial', 'Reporte Financiero'), ('marketing', 'Reporte de Marketing'), ('performance', 'Reporte de Rendimiento')], max_length=20, verbose_name='Tipo de Reporte')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral')], max_length=20, verbose_name='Frecuencia')),
                ('email_delivery', models.BooleanField(default=True, verbose_name='Entrega por Email')),
                ('dashboard_notification', models.BooleanField(default=True, verbose_name='Notificación en Dashboard')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Último Envío')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Envío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción a Reporte',
                'verbose_name_plural': 'Suscripciones a Reportes',
                'unique_together': {('user', 'report_type', 'frequency')},
            },
        ),
    ]
