# Generated by Django 4.2.7 on 2025-10-09 15:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('alert_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('notification', 'Notificación'), ('warning', 'Advertencia'), ('info', 'Información'), ('success', 'Éxito'), ('error', 'Error')], default='info', max_length=20, verbose_name='Tipo de alerta')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('read', 'Leída'), ('dismissed', 'Descartada'), ('expired', 'Expirada')], default='active', max_length=20, verbose_name='Estado')),
                ('scheduled_at', models.DateTimeField(verbose_name='Programada para')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira en')),
                ('frequency', models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='once', max_length=20, verbose_name='Frecuencia')),
                ('icon', models.CharField(default='bell', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='URL de acción')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='Texto de acción')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es recurrente')),
                ('is_system_alert', models.BooleanField(default=False, verbose_name='Alerta del sistema')),
                ('send_email', models.BooleanField(default=False, verbose_name='Enviar por email')),
                ('send_push', models.BooleanField(default=True, verbose_name='Enviar notificación push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído en')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Descartado en')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('title_template', models.CharField(max_length=200, verbose_name='Plantilla del título')),
                ('message_template', models.TextField(verbose_name='Plantilla del mensaje')),
                ('alert_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('notification', 'Notificación'), ('warning', 'Advertencia'), ('info', 'Información'), ('success', 'Éxito'), ('error', 'Error')], default='reminder', max_length=20, verbose_name='Tipo de alerta')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('frequency', models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='weekly', max_length=20, verbose_name='Frecuencia')),
                ('advance_time', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Tiempo de anticipación')),
                ('icon', models.CharField(default='bell', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Alerta',
                'verbose_name_plural': 'Plantillas de Alertas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('trigger_type', models.CharField(choices=[('date_based', 'Basada en fecha'), ('event_based', 'Basada en evento'), ('condition_based', 'Basada en condición'), ('time_based', 'Basada en tiempo')], max_length=20, verbose_name='Tipo de disparador')),
                ('trigger_condition', models.JSONField(default=dict, verbose_name='Condición del disparador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Último disparo')),
                ('target_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios objetivo')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alerttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alertas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('delivered', 'Entregada'), ('failed', 'Fallida'), ('read', 'Leída')], default='pending', max_length=20, verbose_name='Estado')),
                ('delivery_method', models.CharField(max_length=50, verbose_name='Método de entrega')),
                ('recipient', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado en')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído en')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerts.alert', verbose_name='Alerta')),
            ],
            options={
                'verbose_name': 'Log de Alerta',
                'verbose_name_plural': 'Logs de Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status'], name='alerts_aler_user_id_286633_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['scheduled_at'], name='alerts_aler_schedul_75af09_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', 'status'], name='alerts_aler_priorit_bae0d8_idx'),
        ),
    ]
