from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserViewSet,
    UserProfileView,
    PasswordChangeView,
    UserStatsView
)

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'', UserViewSet, basename='user')

urlpatterns = [
    # User CRUD operations via ViewSet
    path('', include(router.urls)),
    
    # Profile management endpoints
    path('me/', UserProfileView.as_view(), name='user-profile'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user-profile-detail'),
    
    # Password change endpoint
    path('change-password/', PasswordChangeView.as_view(), name='change-password'),
    
    # User statistics (Admin only)
    path('stats/', UserStatsView.as_view(), name='user-stats'),
]

# URL patterns generated by the router:
# GET /users/ - List all users
# POST /users/ - Create a new user (Admin only)
# GET /users/{id}/ - Retrieve a specific user
# PUT /users/{id}/ - Update a specific user
# PATCH /users/{id}/ - Partially update a specific user
# DELETE /users/{id}/ - Delete a specific user
# GET /users/me/ - Get current user profile
# POST /users/{id}/assign-role/ - Assign role to user (Admin only)