# Generated by Django 4.2.7 on 2025-10-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(help_text='Clase CSS del icono', max_length=50, verbose_name='Icono')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('section_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('properties', 'Propiedades'), ('clients', 'Clientes'), ('activities', 'Actividades'), ('reports', 'Reportes'), ('contracts', 'Contratos'), ('messages', 'Mensajería'), ('alerts', 'Alertas'), ('networks', 'Redes'), ('settings', 'Configuración')], max_length=20, verbose_name='Tipo de Sección')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_permission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Permiso Requerido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.menusection', verbose_name='Sección Padre')),
            ],
            options={
                'verbose_name': 'Sección del Menú',
                'verbose_name_plural': 'Secciones del Menú',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('activity', 'Actividad'), ('message', 'Mensaje')], default='info', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('action_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL de Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Último Acceso')),
                ('current_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.menusection', verbose_name='Sección Actual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Navegación del Usuario',
                'verbose_name_plural': 'Navegación de Usuarios',
                'unique_together': {('user',)},
            },
        ),
    ]
